parameters:
- name: productionRelease
  displayName: 'Build package for a production release (non-preview)'
  type: boolean
  default: false

steps:
  # split the following two scripts
  # because of not working issue on windows platform.
  - script: |
      npm install -g vsce
    displayName: Install vsce

  - ${{ if eq(parameters.productionRelease, false) }}:
    - script: |
        vsce package --pre-release
      displayName: Build pre-release VSIX Package

  - ${{ if eq(parameters.productionRelease, true) }}:
    - script: |
        vsce package
      displayName: Build VSIX Package

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: '**/*.vsix'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  
  - task: AzureArtifacts.manifest-generator-task.manifest-generator-task.ManifestGeneratorTask@0
    displayName: 'Generate Software Manifest'
    inputs:
      BuildDropPath: '$(Build.ArtifactStagingDirectory)'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifactType: 'pipeline'
      artifactName: vscode-dtdl
